<?xml version="1.0" encoding="UTF-8"?>
<odoo>
	<data noupdate="1">
    <!-- Error Email template  -->
    <record id="meli_cron_error_mailer" model="mail.template">
        <field name="name">Meli Error</field>
        <field name="email_from">${object.email or ''}</field>
        <field name="email_to">${object.email or ''}</field>
        <field name="subject">[DB ${ctx.get('dbname')}] Scheduler '${object.name or ''}' FAILED</field>
        <!--<field name="model_id" ref="base.model_ir_cron"/>-->
        <field name="model_id" ref="account.model_res_company"/>
        <field name="auto_delete" eval="True"/>
        <field name="body_html">
            <![CDATA[
  <div style="font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; ">
  <p>Meli Odoo tried to refresh credentials for <em>${object.name or ''}</em> in the database <em>${ctx.get('dbname')}</em> but it failed. Here is the error message :</p>
  <strong>
  ${ctx.get('job_exception') or 'Failed to get the error message from the context.'}
  </strong>
  <p>Log into Odoo then click here: <a href="${object.mercadolibre_redirect_uri}" target="_blank">Meli Login</a></p>
  <p>
  -- <br/>
  Automatic e-mail sent by Odoo. Do not reply.<br/>
  Database : ${ctx.get('dbname')}
  </p>
  </div>
  ]]>
        </field>
      </record>
    </data>
</odoo>
